### ISSUE TITLE
not decoding the file throws an error 

### ISSUE THREAD

**Issue by abdullahrehan430** [wix-incubator/react-native-opus-decode#2]
Error: Requiring module "node_modules/react-native-opus-decode/src/index.tsx", which threw an exception: Invariant Violation: Native module cannot be null.

 const localWavPath = await decodeOpus(
      'https://filesamples.com/samples/audio/opus/sample4.opus',
    );
    console.log(localWavPath);
I don't know why this is hapening but i am not able to use this library

**Comment by doronpr** [comment]
Hi - this lib requires [react-native-fs](https://github.com/itinance/react-native-fs)
Can you install it on your app and LMK if it works?
I'll update the docs

**Comment by abdullahrehan430** [comment]
Hey bro thanks for your reply , after installing the library it start working  . But I have one more problem , I need to play this decoded file with react-native-sound-player ,

the path i am getting is follwoing
/var/mobile/Containers/Data/Application/uuid/Library/Caches/tmp-3d814358-d3ff-4c9b-82b8-99afc6035828.wav

and i am passing it to the the player as below :
SoundPlayer.playSoundFile(localWavPath, 'wav');

the sound is not playing by the player  , do you know any other library for this or what i am missing in case of passing the path ?? 
also the documentation said that it will play files on from bundle , so this decoded file is in app bundle or device storage??

thanks for your response in advance

**Comment by doronpr** [comment]
Hey, the output format is actually `pcm` and not `wav`.
I'll fix it as it's misleading.
Let me know if this works.

**Comment by doronpr** [comment]
Also I was able to play the file using `react-native-sound`, maybe try that lib?

**Comment by abdullahrehan430** [comment]
I am very thankful for your time , you really saves my time , react-native-sound plays this audio. 
Thanks for your great work😊😊

**Comment by abdullahrehan430** [comment]
this issue has been solved
