### ISSUE TITLE
unable to build in xocde on react-native 0.70.6

### ISSUE THREAD

**Issue by rehan-taiftec** [wix-incubator/react-native-opus-decode#5]
react-native-opus-decode version : "^0.22.1"
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 110.66 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2023.01.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Error 
Multiple commands produce '/Users/abdullahrehan/Library/Developer/Xcode/DerivedData/FlashLead-dxboqgdchdswzidqfdehxfcbvkwk/Build/Products/Debug-iphonesimulator/react-native-opus-decode/react_native_opus_decode.framework/Headers/decoder.h'

just upgrade the project form 0.64 to 0.70.6 project is working fine on android but on ios throws the above error

**Comment by berkayakin** [comment]
I am having the same issue. Any update?

**Comment by berkayakin** [comment]
Should we expect an update to support latest React? @doronpr 
If not, I will need to look for alternative solutions. Thanks!

**Comment by doronpr** [comment]
Hi - I will try to get to this week and update

**Comment by berkayakin** [comment]
Thank you!

**Comment by doronpr** [comment]
Hey @berkayakin @rehan-taiftec  I upgraded to RN 0.70 and wasn't able to reproduce your issue.
I did however found a duplicate file in the project which may be cause of your issue.
Can you checkout this branch: https://github.com/wix-incubator/react-native-opus-decode/pull/10
If this resolves your problem I will merge it.

**Comment by berkayakin** [comment]
@doronpr I can confirm that this branch fixes the issue. Thanks! My RN version is `0.71.3`.

Can we also expect a native Apple Silicon support?

**Comment by doronpr** [comment]
fixed in [0.22.7](https://github.com/wix-incubator/react-native-opus-decode/commit/79ca92ac9ac8359efc1fa3a7b8f50c3720b31d37)

Regarding the Silicon support. Let's discuss in https://github.com/wix-incubator/react-native-opus-decode/issues/4
